// examples/frontend/src/App.tsx
// src/App.tsx

import { launch } from '@onboarden/importer';
import React, { useEffect, useState } from 'react';

const TEMPLATE_ID = 'YOUR TEMPLATE ID';

function App() {
  const [token, setToken] = useState<string | undefined>();

  useEffect(() => {
    getToken();
  }, []);

  const getToken = async () => {
    const response = await fetch('http://localhost:8000');
    const { token } = await response.json();
    setToken(token);
  };

  const launchImporter = () => {
    launch({
      templateId: TEMPLATE_ID,
      jwt: token,
      onCompleted: (result) => console.log(result),
    });
  };

  return (
    <div>
      <button onClick={launchImporter} disabled={token === undefined}>
        Import
      </button>
    </div>
  );
}

export default App;

// examples/vue/src/App.vue
<!--  src/App.vue -->

<script lang="ts">
import { launch } from "@onboarden/importer";

const TEMPLATE_ID = "YOUR TEMPLATE ID";

export default {
  methods: {
    open: async () => {
      const response = await fetch("http://localhost:8000");
      const { token } = await response.json();

      launch({
        templateId: TEMPLATE_ID,
        jwt: token,
        onCompleted: (result) => console.log(result),
      });
    },
  },
};
</script>

<template>
  <main>
    <button @click="open">Import</button>
  </main>
</template>
