// examples/vue/src/AppNoAuth.vue
<!--  src/App.vue -->

<script lang="ts">
import { launch } from "@onboarden/importer";

const TEMPLATE_ID = "YOUR TEMPLATE ID";

export default {
  methods: {
    open: async () => {
      launch({
        templateId: TEMPLATE_ID,
        onCompleted: (result) => console.log(result),
      });
    },
  },
};
</script>

<template>
  <main>
    <button @click="open">Import</button>
  </main>
</template>

// examples/react/src/AppNoAuth.tsx
// src/App.tsx

import { launch } from "@onboarden/importer";
import React from "react";

const TEMPLATE_ID = "YOUR TEMPLATE ID";

function App() {
  const launchImporter = async () => {
    launch({
      templateId: TEMPLATE_ID,
      onCompleted: (result) => console.log(result),
    });
  };

  return (
    <div>
      <button onClick={launchImporter}>Import</button>
    </div>
  );
}

export default App;
